### ISSUE TITLE
#3742 leads to HIP compile issues

### ISSUE THREAD

**Issue by baperry2** [AMReX-Codes/amrex#3759] opened 2024-02-14 00:21 UTC
Recent changes in AMReX (narrowed down to #3742) cause the CI of PelePhysics to fail when compiling with HIP. Results in a bunch of errors like the following at the linking stage (works fine for AMReX before the linked PR):

```
MDNode incompatible with Debug Info Version
!DIExpression(DW_OP_LLVM_arg, 0, DW_OP_LLVM_arg, 1, DW_OP_LLVM_arg, 2, DW_OP_LLVM_arg, 3, DW_OP_mul, DW_OP_minus, DW_OP_LLVM_convert, 64, DW_ATE_unsigned, DW_OP_LLVM_convert, 32, DW_ATE_unsigned, DW_OP_plus, DW_OP_stack_value)
4
debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.value(metadata !DIArgList(i32 poison, i64 poison, i64 poison, i64 poison), metadata !19049, metadata !DIExpression(DW_OP_LLVM_arg, 0, DW_OP_LLVM_arg, 1, DW_OP_LLVM_arg, 2, DW_OP_LLVM_arg, 3, DW_OP_mul, DW_OP_minus, DW_OP_LLVM_convert, 64, DW_ATE_unsigned, DW_OP_LLVM_convert, 32, DW_ATE_unsigned, DW_OP_plus, DW_OP_stack_value)), !dbg !19151
4

...

debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.value(metadata i32 %84, metadata !118564, metadata !DIExpression(DW_OP_plus_uconst, 4)), !dbg !118605
4
debug intrinsic incompatible with Debug Info Version
  call void @llvm.dbg.value(metadata i32 %84, metadata !118565, metadata !DIExpression(DW_OP_plus_uconst, 8)), !dbg !118605
4
LLVM ERROR: Broken module found, compilation aborted!
```

See here for full info on failed run:
https://github.com/AMReX-Combustion/PelePhysics/actions/runs/7891352293/job/21540279251?pr=476

**Comment by yut23** [comment] 2024-02-14 00:39
Coincidentally, I've been tracking this down this evening as well. I can reproduce this with the `Amr/Advection_AmrCore` and `GPU/Vector` test cases on Frontier with ROCm 5.3.0 through 5.7.1, while it works fine with 5.2.0 and 6.0.0.

**Comment by WeiqunZhang** [comment] 2024-02-14 00:51
Looks it compiles without `-g`.

**Comment by WeiqunZhang** [comment] 2024-02-14 00:53
`-g1` also works

**Comment by WeiqunZhang** [comment] 2024-02-14 01:02
Okay `-gline-tables-only -fdebug-info-for-profiling` also works. Let's use these two options just like for Intel compilers. The two options were recommended by Intel VTune.

https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-gline-tables-only
https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fdebug-info-for-profiling

**Comment by WeiqunZhang** [comment] 2024-02-14 01:34
I am able to reproduce the issue with Amr/Advection_AmrCore thanks to @yut23's tip. PR #3761 solves the issue in my testing. @baperry2 could you test to see if it resolves the issue for PelePhysics?

**Comment by baperry2** [comment] 2024-02-14 04:25
@WeiqunZhang I can confirm that these changes resolve the issue for PelePhysics. Thanks for the quick solution!

The issue appeared for us using ROCM 5.6.1, although @jrood-nrel suspected going to 6.0 might fix the issue.

**Comment by yut23** [comment] 2024-02-14 21:06
After more investigation into the innards of the ROCm LLVM fork, the source of the issue is the structured binding declarations used with `BoxIndexer`. Extracting `i, j, k` manually works as expected, without needing any new compiler flags. For reference, it was fixed in this commit (backported to 6.0.0): https://github.com/ROCm/llvm-project/commit/90eeeb123ad42527d22828729361733994111b8b (hooray for open source!)

**Comment by WeiqunZhang** [comment] 2024-02-14 21:15
Interesting. Thanks for the information!

**Comment by yut23** [comment] 2024-02-16 18:48
For the last piece of the puzzle, here's where it was introduced in 5.3.0: https://github.com/ROCm/llvm-project/commit/f56cb520d8554ca42a215e82ecfa58d0b6c178e4

**Closed as completed** 2024-02-23 02:19 UTC
