### ISSUE TITLE
Commit be25c21d broke for the NAG Fortran compiler

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#241] opened 2018-04-06 16:00 UTC
Commit be25c21 reworked some Fortran code (conversion from f77 to f90?) and in the process relied on some C processor features not recognized by the NAG compiler (and generally not regarded as Fortran preprocessing directives). Culprit files are `AMReX_COORDSYS_3D.F90` and the `1D` and `2D` versions; there may be others.  They include the new header file `AMRex_COORDSYS_F.H` which defines a bunch of macros like `DIM` which use the concatenation operator ## or an apparent alternative /**/ (empty C comment?).  It seems like this issue has cropped up before (and been fixed).

**Comment by maxpkatz** [comment] 2018-04-06 16:11
That commit did not involve any change to code, and that is not a new header file. Something about the change to running them through the F90 compiler instead of the F77 compiler must have broken this for NAG.

**Comment by nncarlson** [comment] 2018-04-06 16:29
Okay, let me investigate further.  Github seemed to indicate these were new files, but perhaps they were just renamed.

**Comment by maxpkatz** [comment] 2018-04-06 16:30
Thanks -- I still think we should fix this if we can, just want to better understand what the actual issue is.

**Comment by WeiqunZhang** [comment] 2018-04-06 16:33
In AMReX build system, `.F` files go through cpp preprocessor invoked by us.  But we don't do that for F90 files.  That's why.

**Comment by WeiqunZhang** [comment] 2018-04-06 16:34
We do not want to call `cpp` ourselves because it makes debug messages clearer if compiler does the preprocessing.

**Comment by nncarlson** [comment] 2018-04-06 16:38
Ah, that's it.
There's a way to define the concatenation operator from more primitive operations. Let me see if I can't fix up the include file for NAG.  Hopefully that is the only issue.

**Comment by WeiqunZhang** [comment] 2018-04-07 01:10
Could you give the latest development branch a try? @nncarlson

**Comment by nncarlson** [comment] 2018-04-07 14:51
@WeiqunZhang I didn't intend for this to distract you from your main work (just yet).  But thanks!  I tried the latest development branch and there are still some macro issues in `AMReX_REAL.H`

Yesterday I used a different approach of fixing the header files for NAG.  I made a PR just now to show you what that looks like.  I should have done the PR earlier, but got distracted by some issues on my end while testing it.  You *might* want to consider it, as it's much less invasive than your changes to source (although the new source that doesn't rely as much on macros is cleaner IMHO).  Note that I don't believe any of my code uses this part of AMReX, so I'm not testing whether the changes are good, just that it compiles.

Also note that the PR changes to `AMReX_REAL.H` likely will fix the remaining errors from your commit.

**Comment by WeiqunZhang** [comment] 2018-04-07 15:42
Could you let me know which Fortran files are still affected by macros in "AMReX_REAL.H"?

**Comment by nncarlson** [comment] 2018-04-07 15:47
`AMReX_LO_UTIL.F90` is the one I'm hitting first (may end up being others after it is fixed).  Basically any Fortran source that uses either the `BL_REAL` and `BL_REAL_E` macros from `AMReX_REAL.H` will need to be fixed.

**Comment by WeiqunZhang** [comment] 2018-04-07 18:43
Yes, I missed `AMReX_LO_UTIL.F90` and `AMReX_ABec_Util.F90`.  I am going to fix these two.  This is good for long term.

**Comment by WeiqunZhang** [comment] 2018-04-07 23:43
I think they are fixed now.

**Comment by nncarlson** [comment] 2018-04-08 15:51
The latest 6c5731c compiles fine with NAG.  Thanks for all your effort @WeiqunZhang !

How do you currently test?  I have a teamcity CI server running at LANL and I could set up a build to monitor the development branch to compile with NAG (and run tests?) any new commit.  It wouldn't be integrated with github of course, but it would allow me to catch issues with the NAG compiler promptly.

**Comment by WeiqunZhang** [comment] 2018-04-11 17:59
We have nightly regression test suits for AMReX and a number of AMReX application codes.  For example, https://ccse.lbl.gov/pub/RegressionTesting/ and http://groot.astro.sunysb.edu/Castro/test-suite/.  These tests use our homegrown tools developed mostly by @zingale.  Some applications choose to have more frequent tests with their own CI server.

It would be great if you could monitor and compile development branch with NAG on your machines and run some tests using your own codes.

**Closed** 2018-11-03 03:59 UTC
