### ISSUE TITLE
CMake Error: string sub-command FIND requires 3 or 4 parameters

### ISSUE THREAD

**Issue by Patistar** [AMReX-Codes/amrex#426] opened 2019-03-19 12:32 UTC
When I try to build the amrex source (I tried master, development and 19.03.1), cmake throws the following error:
```
CMake Error at Tools/CMake/AMReX_Utils.cmake:382 (string):
  string sub-command FIND requires 3 or 4 parameters.
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:188 (replace_genex)
  Tools/CMake/AMReX_Config.cmake:150 (print_amrex_configuration_summary)
  Src/CMakeLists.txt:47 (configure_amrex)
```

This happens when the replace_genex replaces CONFIGRelease and CONFIGDebug with empty strings. I added a few message functions with the following output:
```
TMP LIST: $<$<CONFIG:Debug>:>;$<$<CONFIG:Release>:>;$<$<CONFIG:RelWithDebInfo>:>;$<$<CONFIG:MinSizeRel>:>;$<BUILD_INTERFACE:$<$<CONFIG:Debug>:$<$<STREQUAL:"GNU","GNU">:$<$<COMPILE_LANGUAGE:Fortran>: -O0 -ggdb -fbounds-check -fbacktrace -Wuninitialized -Wunused -finit-real=snan -finit-integer=2147483647>>>>;$<BUILD_INTERFACE:$<$<CONFIG:Release>:$<$<STREQUAL:"GNU","GNU">:$<$<COMPILE_LANGUAGE:Fortran>: >>>>;$<BUILD_INTERFACE:$<$<CONFIG:Debug>:$<$<STREQUAL:"GNU","Intel">:$<$<COMPILE_LANGUAGE:Fortran>: -O0 -traceback -check bounds,uninit,pointers>>>>;$<BUILD_INTERFACE:$<$<CONFIG:Release>:$<$<STREQUAL:"GNU","Intel">:$<$<COMPILE_LANGUAGE:Fortran>: -ip -qopt-report=5 -qopt-report-phase=vec>>>>;$<BUILD_INTERFACE:$<$<CONFIG:Debug>:$<$<STREQUAL:"GNU","Cray">:$<$<COMPILE_LANGUAGE:Fortran>: -O0 -e i>>>>;$<BUILD_INTERFACE:$<$<CONFIG:Release>:$<$<STREQUAL:"GNU","Cray">:$<$<COMPILE_LANGUAGE:Fortran>: >>>>;$<BUILD_INTERFACE:$<$<CONFIG:Debug>:$<$<STREQUAL:"GNU","PGI">:$<$<COMPILE_LANGUAGE:Fortran>: -O0 -Mbounds -Mchkptr>>>>;$<BUILD_INTERFACE:$<$<CONFIG:Release>:$<$<STREQUAL:"GNU","PGI">:$<$<COMPILE_LANGUAGE:Fortran>: -gopt -fast>>>>;$<$<STREQUAL:"GNU","GNU">:$<$<COMPILE_LANGUAGE:Fortran>: -ffixed-line-length-none -ffree-line-length-none >>;$<$<STREQUAL:"GNU","Intel">:$<$<COMPILE_LANGUAGE:Fortran>: -extend_source>>;$<$<STREQUAL:"GNU","Cray">:$<$<COMPILE_LANGUAGE:Fortran>: -N 255 -h list=a>>;$<$<STREQUAL:"GNU","PGI">:$<$<COMPILE_LANGUAGE:Fortran>: -Mextend>>;$<$<CXX_COMPILER_ID:Cray>:$<$<COMPILE_LANGUAGE:CXX>:-h std=c++11 -h list=a>>;$<$<CXX_COMPILER_ID:PGI>:$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>>;$<$<CXX_COMPILER_ID:Clang>:$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>>;$<$<CXX_COMPILER_ID:AppleClang>:$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>>;$<$<CXX_COMPILER_ID:GNU>:$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>>;$<$<CXX_COMPILER_ID:Intel>:$<$<COMPILE_LANGUAGE:CXX>:-std=c++11>>;$<$<COMPILE_LANGUAGE:Fortran>:>;$<$<COMPILE_LANGUAGE:C>:>;$<$<COMPILE_LANGUAGE:CXX>:>;$<$<CXX_COMPILER_ID:Cray>:-h noomp>;$<$<C_COMPILER_ID:Cray>:-h noomp>
ITEM 1: CONFIGDebug
ITEM 1: CONFIGRelease
ITEM 2:
CMake Error at Tools/CMake/AMReX_Utils.cmake:382 (string):
  string sub-command FIND requires 3 or 4 parameters.
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:188 (replace_genex)
  Tools/CMake/AMReX_Config.cmake:150 (print_amrex_configuration_summary)
  Src/CMakeLists.txt:47 (configure_amrex)
```
TMP LIST is at the next line after 318,
ITEM 1 is at the next line after 331,
ITEM 2 is at the next line after 372

I build with Conan using these settings:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
```
CMake Version 3.13.4

**Comment by Patistar** [comment] 2019-03-20 14:59
I put some further investigation into the issue. It can be fixed by using
```
string ( FIND "${item}" "COMPILE_LANGUAGE" idx1 )
```
instead of
```
string ( FIND ${item} "COMPILE_LANGUAGE" idx1 )
```

**Comment by mic84** [comment] 2019-04-04 21:32
Hi Patistar,
could you reproduce with a direct build, i.e. without using Conan, and post the CMake invocation here?
Thanks.

**Comment by asalmgren** [comment] 2019-04-20 23:08
Is this issue still a problem, or can it be closed?

**Comment by Patistar** [comment] 2019-04-23 09:13
Sorry for the late reply, I've been on holidays the last three weeks.

@mic84 When I do a direct build, I don't run into the issue and everything works fine.
`cmake -DCMAKE_PREFIX_PATH=/Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b ..`

<details><summary>The direct build outputs the following (click on the arrow):</summary>

```.
> cmake -DCMAKE_PREFIX_PATH=/Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b ..
-- Setting build type to Release as none was specified.
-- Configuring AMReX with the following options:
--    USE_XSDK_DEFAULTS = OFF
--    BUILD_SHARED_LIBS = OFF
--    CMAKE_INSTALL_PREFIX = /tmp/amrex/amrex/installdir
--    DIM = 3
--    ENABLE_PIC = OFF
--    ENABLE_MPI = ON
--    ENABLE_OMP = OFF
--    ENABLE_CUDA = OFF
--    ENABLE_DP = ON
--    ENABLE_EB = OFF
--    ENABLE_FORTRAN_INTERFACES = ON
--    ENABLE_LINEAR_SOLVERS = ON
--    ENABLE_AMRDATA = OFF
--    ENABLE_PARTICLES = OFF
--    ENABLE_SENSEI_INSITU = OFF
--    ENABLE_3D_NODAL_MLMG = OFF
--    ENABLE_FPE = OFF
--    ENABLE_ASSERTIONS = OFF
--    ENABLE_BASE_PROFILE = OFF
--    ENABLE_TINY_PROFILE = OFF
--    ENABLE_TRACE_PROFILE = OFF
--    ENABLE_MEM_PROFILE = OFF
--    ENABLE_COMM_PROFILE = OFF
--    ENABLE_BACKTRACE = OFF
--    ENABLE_PROFPARSER = OFF
--    TP_PROFILE = None
-- Machine name is UnknownMac.local
-- Site name is unknown
-- Fortran name mangling scheme: UNDERSCORE (lower case, append underscore)
-- AMReX configuration summary:
--    Build type               = Release
--    Install directory        = /tmp/amrex/amrex/installdir
--    C++ defines              = -DAMREX_GIT_VERSION="19.03.1" -DAMREX_USE_MPI -DBL_USE_MPI -DAMREX_SPACEDIM=3 -DBL_SPACEDIM=3 -DAMREX_Darwin -DBL_Darwin -DAMREX_USE_F_INTERFACES -DBL_USE_F_INTERFACES -DAMREX_NO_STRICT_PREFIX -DBL_NO_STRICT_PREFIX -DAMREX_FORT_USE_UNDERSCORE -DBL_FORT_USE_UNDERSCORE
--    Fortran defines          = -DAMREX_GIT_VERSION="19.03.1" -DAMREX_USE_MPI -DBL_USE_MPI -DAMREX_SPACEDIM=3 -DBL_SPACEDIM=3 -DAMREX_Darwin -DBL_Darwin -DAMREX_USE_F_INTERFACES -DBL_USE_F_INTERFACES -DAMREX_NO_STRICT_PREFIX -DBL_NO_STRICT_PREFIX -DBL_LANG_FORT -DAMREX_LANG_FORT -DAMREX_FORT_USE_UNDERSCORE -DBL_FORT_USE_UNDERSCORE
--    C++ compiler             = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--    Fortran compiler         = /usr/local/bin/gfortran
--    C++ flags                = -O3 -DNDEBUG  -std=c++11
--    Fortran flags            = -O3 -DNDEBUG -O3     -ffixed-line-length-none -ffree-line-length-none
--    C++ include paths        = /tmp/amrex/amrex/build/mod_files;/Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/include
--    Fortran include paths    = /tmp/amrex/amrex/build/mod_files;/Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/include
--    Link line                = /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi_mpifh.a /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi.a /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libopen-rte.a /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libopen-pal.a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd /Users/Patrick/.conan/data/zlib/1.2.11/conan/stable/package/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583/lib/libz.a
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/amrex/amrex/build
```

</details>

<details><summary>The conan output looks like this (click on the arrow):</summary>

```.
> conan create . AMReX/19.03.1@reactive-euler/stable
Exporting package recipe
AMReX/19.03.1@reactive-euler/stable: A new conanfile.py version was exported
AMReX/19.03.1@reactive-euler/stable: Folder: /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/export
AMReX/19.03.1@reactive-euler/stable: Package recipe modified in export, forcing source folder removal
AMReX/19.03.1@reactive-euler/stable: Use the --keep-source, -k option to skip it
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

AMReX/19.03.1@reactive-euler/stable: WARN: Forced build from source
Version ranges solved
    Version range '>=1.2.11' required by 'OpenMPI/3.1.3@reactive-euler/stable' resolved to 'zlib/1.2.11@conan/stable'

AMReX/19.03.1@reactive-euler/stable (test package): Installing package
Requirements
    AMReX/19.03.1@reactive-euler/stable from local cache - Cache
    OpenMPI/3.1.3@reactive-euler/stable from 'reactive-euler' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    AMReX/19.03.1@reactive-euler/stable:c82f72bbf9ef26ffe56c738232c53c0fd9a7289f - Build
    OpenMPI/3.1.3@reactive-euler/stable:13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b - Cache
    zlib/1.2.11@conan/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583 - Cache

zlib/1.2.11@conan/stable: Already installed!
OpenMPI/3.1.3@reactive-euler/stable: Already installed!
AMReX/19.03.1@reactive-euler/stable: Building your package in /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f
AMReX/19.03.1@reactive-euler/stable: Configuring sources in /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/source
Klone nach 'amrex' ...
remote: Enumerating objects: 583, done.
remote: Counting objects: 100% (583/583), done.
remote: Compressing objects: 100% (474/474), done.
remote: Total 208771 (delta 459), reused 153 (delta 98), pack-reused 208188
Empfange Objekte: 100% (208771/208771), 474.70 MiB | 9.18 MiB/s, Fertig.
Löse Unterschiede auf: 100% (163386/163386), Fertig.
Hinweis: Checke '884d3194c9d890fcd135e44ef48b8b9886d87c9c' aus.

Sie befinden sich im Zustand eines 'losgelösten HEAD'. Sie können sich
umschauen, experimentelle Änderungen vornehmen und diese committen, und
Sie können alle möglichen Commits, die Sie in diesem Zustand machen,
ohne Auswirkungen auf irgendeinen Branch verwerfen, indem Sie einen
weiteren Checkout durchführen.

Wenn Sie einen neuen Branch erstellen möchten, um Ihre erstellten Commits
zu behalten, können Sie das (jetzt oder später) durch einen weiteren Checkout
mit der Option -b tun. Beispiel:

  git checkout -b <neuer-Branchname>

Checke Dateien aus: 100% (2768/2768), Fertig.
AMReX/19.03.1@reactive-euler/stable: Copying sources to build folder
AMReX/19.03.1@reactive-euler/stable: Generator cmake created conanbuildinfo.cmake
AMReX/19.03.1@reactive-euler/stable: Calling build()
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: C++ stdlib: libc++
-- The Fortran compiler identification is GNU 8.3.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- Build type set by user to 'Release'.
-- Configuring AMReX with the following options:
--    USE_XSDK_DEFAULTS = OFF
--    BUILD_SHARED_LIBS = OFF
--    CMAKE_INSTALL_PREFIX = /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/package/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f
--    DIM = 3
--    ENABLE_PIC = OFF
--    ENABLE_MPI = ON
--    ENABLE_OMP = OFF
--    ENABLE_CUDA = OFF
--    ENABLE_DP = ON
--    ENABLE_EB = ON
--    ENABLE_FORTRAN_INTERFACES = ON
--    ENABLE_LINEAR_SOLVERS = ON
--    ENABLE_AMRDATA = OFF
--    ENABLE_PARTICLES = OFF
--    ENABLE_SENSEI_INSITU = OFF
--    ENABLE_3D_NODAL_MLMG = OFF
--    ENABLE_FPE = OFF
--    ENABLE_ASSERTIONS = OFF
--    ENABLE_BASE_PROFILE = OFF
--    ENABLE_TINY_PROFILE = OFF
--    ENABLE_TRACE_PROFILE = OFF
--    ENABLE_MEM_PROFILE = OFF
--    ENABLE_COMM_PROFILE = OFF
--    ENABLE_BACKTRACE = OFF
--    ENABLE_PROFPARSER = OFF
--    TP_PROFILE = None
-- Machine name is UnknownMac.local
-- Site name is unknown
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Fortran name mangling scheme: UNDERSCORE (lower case, append underscore)
-- Found MPI_C: /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi.a (found version "3.1")
-- Found MPI_CXX: /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi.a (found version "3.1")
-- Found MPI_Fortran: /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi_mpifh.a (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
CMake Error at Tools/CMake/AMReX_Utils.cmake:376 (string):
  string sub-command FIND requires 3 or 4 parameters.
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:187 (replace_genex)
  Tools/CMake/AMReX_Config.cmake:150 (print_amrex_configuration_summary)
  Src/CMakeLists.txt:47 (configure_amrex)


CMake Error at Tools/CMake/AMReX_Utils.cmake:376 (string):
  string sub-command FIND requires 3 or 4 parameters.
Call Stack (most recent call first):
  Tools/CMake/AMReX_Config.cmake:188 (replace_genex)
  Tools/CMake/AMReX_Config.cmake:150 (print_amrex_configuration_summary)
  Src/CMakeLists.txt:47 (configure_amrex)


-- AMReX configuration summary:
--    Build type               = Release
--    Install directory        = /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/package/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f
--    C++ defines              = -DAMREX_GIT_VERSION="19.03.1-dirty" -DAMREX_USE_MPI -DBL_USE_MPI -DAMREX_SPACEDIM=3 -DBL_SPACEDIM=3 -DAMREX_Darwin -DBL_Darwin -DAMREX_USE_EB -DBL_USE_EB -DAMREX_USE_F_INTERFACES -DBL_USE_F_INTERFACES -DAMREX_NO_STRICT_PREFIX -DBL_NO_STRICT_PREFIX -DAMREX_FORT_USE_UNDERSCORE -DBL_FORT_USE_UNDERSCORE
--    Fortran defines          = -DAMREX_GIT_VERSION="19.03.1-dirty" -DAMREX_USE_MPI -DBL_USE_MPI -DAMREX_SPACEDIM=3 -DBL_SPACEDIM=3 -DAMREX_Darwin -DBL_Darwin -DAMREX_USE_EB -DBL_USE_EB -DAMREX_USE_F_INTERFACES -DBL_USE_F_INTERFACES -DAMREX_NO_STRICT_PREFIX -DBL_NO_STRICT_PREFIX -DBL_LANG_FORT -DAMREX_LANG_FORT -DAMREX_FORT_USE_UNDERSCORE -DBL_FORT_USE_UNDERSCORE
--    C++ compiler             = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--    Fortran compiler         = /usr/local/bin/gfortran
--    C++ flags                = -O3 -DNDEBUG    -m64 -stdlib=libc++ -std=c++11
--    Fortran flags            = -O3 -DNDEBUG -O3     -ffixed-line-length-none -ffree-line-length-none
--    C++ include paths        = /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f/mod_files;/Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/include
--    Fortran include paths    = /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f/mod_files;/Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/include
--    Link line                = /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi_mpifh.a /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libmpi.a /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libopen-rte.a /Users/Patrick/.conan/data/OpenMPI/3.1.3/reactive-euler/stable/package/13beec987e7b1d86f43a2d5ce80dc3f1a3d7954b/lib/libopen-pal.a /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd /Users/Patrick/.conan/data/zlib/1.2.11/conan/stable/package/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583/lib/libz.a
-- Configuring incomplete, errors occurred!
See also "/Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f/CMakeFiles/CMakeOutput.log".
AMReX/19.03.1@reactive-euler/stable:
AMReX/19.03.1@reactive-euler/stable: ERROR: Package 'c82f72bbf9ef26ffe56c738232c53c0fd9a7289f' build failed
AMReX/19.03.1@reactive-euler/stable: WARN: Build folder /Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f
ERROR: AMReX/19.03.1@reactive-euler/stable: Error in build() method, line 42
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 36
	"ENABLE_EB": "ON" if self.options.eb else "OFF"
	ConanException: Error 256 while executing cd '/Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="10.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libc++" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/package/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev -DENABLE_MPI="ON" -DENABLE_EB="ON" '/Users/Patrick/.conan/data/AMReX/19.03.1/reactive-euler/stable/build/c82f72bbf9ef26ffe56c738232c53c0fd9a7289f/amrex'
```

</details>

Not sure if you want to address this issue, when it is only related to conan. But if you need more details or information let me know. I'm happy to help wherever I can.

**Comment by mic84** [comment] 2019-04-23 17:31
Hi @Patistar ,
thanks for reporting back. I notice only now that you are building on a Mac. While many of our users build AMReX on Macs, we officially support only Linux systems. Also, it does seem the problem is related to Conan rather than AMReX: I did tried a build on a Mac and it worked without any issue.

That said, the CMake function the error message points to has been replaced in the development branch. You may want to try that branch and see if it solve the issue. Let me know if using the latest AMReX helps. Thank you.

**Comment by Patistar** [comment] 2019-04-23 20:44
Hi @mic84,
thanks for your quick reply. Using the development branch, the build with conan works perfectly fine and resolves the issue.
Looking forward to the 19.05 release! Thanks! :)

**Comment by mic84** [comment] 2019-04-23 20:59
Glad to hear. Closing the issue.

**Closed by mic84** 2019-04-23 20:59 UTC
