### ISSUE TITLE
particle redistribute when using cuda

### ISSUE THREAD

**Issue by hsitaram** [AMReX-Codes/amrex#1410] opened 2020-09-25 03:57 UTC
Hi

I was working on a project that used a similar structure as the amrex/Tutorials/Particles/NeighborList and I am getting some weird behavior when calling redistribute instead of redistributelocal. I think I understand that redistribute is a more thorough exchange compared to redistributelocal.

when I make this slight change in main.cpp in amrex/Tutorials/Particles/NeighborList 

//pc.RedistributeLocal();
 pc.Redistribute();

 if (params.print_min_dist     ) amrex::Print() << "Min distance  is " << min_d << "\n";
 if (params.print_num_particles) amrex::Print() << "Num particles is " << pc.TotalNumberOfParticles() << "\n";

I get this in the outputs

Initializing CUDA...
CUDA initialized with 1 GPU per MPI rank; 1 GPU(s) used in total
MPI initialized with 1 MPI processes
MPI initialized with thread support level 0
AMReX (20.04-738-g605e276d42d6) initialized
Running MD benchmark
Num particles after init is **262144**
Num particles is **157650**

I was wondering why the particle number is reducing. It should remain the same in this case as the domain boundaries are walls. There is a reflection done in moveparticles.
**I also don't see the same issue on CPU.**  It gives the same particle numbers.

I hope I am not using redistribute incorrectly. I am using the amrex development updated on sep 24th, 2020.

Thanks,
Hari

**Comment by atmyers** [comment] 2020-09-25 19:59
Thank you for pointing this out. The issue is that the neighbor particles need to cleared before calling Redistribute(). This was happening automatically for the local version, but not the global one. When PR 1415 is merged, this should be fixed.

**Comment by hsitaram** [comment] 2020-09-25 21:47
Thank you @atmyers. Using clearneighbors before redistribute worked correctly on GPU. Although, I am puzzled how it was working ok on CPU. I can use the new branch and remove this call.

**Closed as completed** 2020-10-29 20:50 UTC
