### ISSUE TITLE
This is not an issue in the code: plotting with YT

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [AMReX-Codes/amrex#221] opened 2018-02-23 21:17 UTC
I have successfully installed the Amrex and could run the following example:
/Tutorials/Amr/Advection_F/Exec/SingleVortex
However, can somebody tell me how to plot the results? I can not install visit on the remote machine (binaries are not working either). I am using the following lines to plot via **yt**:

`ds = yt.load("plt00010")`

`slc = yt.SlicePlot(ds, 'z', 'phi')`

`slc.show()`
But I get the following error:

`interactivity = self.plots[list(self.plots.keys())[0]].interactivity`

`indexError: list index out of range`

--------------------------------------------------------------------------------------------------------------------------------------
The rest of the output:
`yt : [INFO     ] 2018-02-23 16:12:49,446 Parameters: current_time              = 0.10986378315417937
yt : [INFO     ] 2018-02-23 16:12:49,446 Parameters: domain_dimensions         = [64 64  1]
yt : [INFO     ] 2018-02-23 16:12:49,446 Parameters: domain_left_edge          = [ 0.  0.  0.] 
yt : [INFO     ] 2018-02-23 16:12:49,446 Parameters: domain_right_edge         = [ 1.  1.  1.]
yt : [INFO     ] 2018-02-23 16:12:49,587 xlim = 0.000000 1.000000
yt : [INFO     ] 2018-02-23 16:12:49,587 ylim = 0.000000 1.000000
yt : [INFO     ] 2018-02-23 16:12:49,588 xlim = 0.000000 1.000000
yt : [INFO     ] 2018-02-23 16:12:49,588 ylim = 0.000000 1.000000
yt : [INFO     ] 2018-02-23 16:12:49,588 Making a fixed resolution buffer of (('boxlib', 'phi')) 800 by 800
yt : [INFO     ] 2018-02-23 16:12:49,614 Making a fixed resolution buffer of (phi) 800 by 800`

**Comment by atmyers** [comment] 2018-02-23 22:05
What you did should work - I'll file an issue with yt and try to find a fix. That said, you can work around by using the full tuple field name instead of just `"phi"` when making your SlicePlot:

`yt.SlicePlot(ds, 'z', ("boxlib", "phi"))`

It should be figuring that out from context, though - not sure why it isn't working at the moment.

**Comment by mahdikooshkbaghi** [comment] 2018-02-23 22:17
Adding the "boxlib" did a trick and I can save now to a png file. Thanks.

**Comment by eschnett** [comment] 2019-07-11 17:15
I just encountered the same issue. If this hasn't been corrected yet, can you update the documentation?

**Comment by atmyers** [comment] 2019-07-11 17:35
I'm unable to reproduce this using the current development version of amrex and current master version of yt. The following code:

```
import yt
ds = yt.load("plt00010")
print(ds.field_list)
slc = yt.SlicePlot(ds, 'z', 'Phi')
slc.show()
```

correct the displays the data for me in a Jupyter notebook. Could you tell me which versions of amrex and yt you are using, and maybe provide a script that triggers the problem for you? Thanks.

**Comment by asalmgren** [comment] 2019-09-03 14:08
@eschnett -- is this still an issue with the current version of amrex?

**Comment by eschnett** [comment] 2019-09-03 15:05
@asalmgren I was able to plot successfully with yt in the end. Unfortunately, yt only seems to handle cell-centred data, and vertex-centred data is plotted wrong (with visible artifacts). I have since switched to VisIt, which is working fine.

**Comment by asalmgren** [comment] 2019-09-03 15:21
Ok, i'll go ahead and close the issue -- thx!

**Closed** 2019-09-03 15:21 UTC
