### ISSUE TITLE
Must add template to the setVal functions

### ISSUE THREAD

**Issue by ldowen** [AMReX-Codes/amrex#743] opened 2020-03-20 16:51 UTC
https://github.com/AMReX-Codes/amrex/blob/1e986786f5b07f59e7bc6bdcbcfc05af04cad796/Src/Particle/AMReX_ParticleContainerI.H#L1626

The `setVal()` functions for BaseFabs should be changed to `template setVal()`. My compiler on the MacOS won't compile without it.

@atmyers

**Comment by drummerdoc** [comment] 2020-03-20 16:55
Yes, when compiling with USE_CUDA=TRUE, this is by design.  All codes will need to be hand-edited.

**Comment by drummerdoc** [comment] 2020-03-20 17:18
...ah, with Clang, you apparently see this requirement even when USE_CUDA=FALSE? The others can probably explain.

**Comment by ldowen** [comment] 2020-03-20 17:26
That is true. I noticed that this step was done when Fabs (or similar data structures) from pointers to MultiFabs (or similar data structures) are modified, like in [https://github.com/AMReX-Codes/amrex/blob/development/Src/Base/AMReX_FabArray.H#L2020](url)

**Comment by WeiqunZhang** [comment] 2020-03-20 17:40
Looks like Clang is more restrictive than gcc.  We will fix it.

**Comment by WeiqunZhang** [comment] 2020-03-20 18:34
I think it's fixed now.

**Closed** 2020-03-20 18:42 UTC
