### ISSUE TITLE
1D AMReX compilation not working

### ISSUE THREAD

**Issue by nncarlson** [AMReX-Codes/amrex#164] opened 2017-11-02 19:23 UTC
A 1D build of AMReX fails with a C++ error (using gcc).   I don't personally care about 1D, but thought I should mention it after discovering it while testing the Fortran replacement for the AMREX_CONSTANTS.H header file
```
/opt/src/amrex/amrex/Src/F_Interfaces/Base/AMReX_geometry_fi.cpp: In function ‘void amrex_fi_new_geometry(amrex::Geometry*&, int*, int*)’:
/opt/src/amrex/amrex/Src/F_Interfaces/Base/AMReX_geometry_fi.cpp:11:28: error: no matching function for call to ‘amrex::Geometry::Geometry(amrex::Box (&)(amrex::IntVect*, amrex::IntVect*))’
  geom = new Geometry(domain);
                            ^
In file included from /opt/src/amrex/amrex/Src/F_Interfaces/Base/AMReX_geometry_fi.cpp:1:0:
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:48:5: note: candidate: constexpr amrex::Geometry::Geometry(amrex::Geometry&&)
     Geometry (Geometry&& rhs) noexcept = default;
     ^~~~~~~~
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:48:5: note:   no known conversion for argument 1 from ‘amrex::Box(amrex::IntVect*, amrex::IntVect*)’ to ‘amrex::Geometry&&’
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:47:5: note: candidate: constexpr amrex::Geometry::Geometry(const amrex::Geometry&)
     Geometry (const Geometry& rhs) = default;
     ^~~~~~~~
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:47:5: note:   no known conversion for argument 1 from ‘amrex::Box(amrex::IntVect*, amrex::IntVect*)’ to ‘const amrex::Geometry&’
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:41:14: note: candidate: amrex::Geometry::Geometry(const amrex::Box&, const amrex::RealBox*, int, int*)
     explicit Geometry (const Box&     dom,
              ^~~~~~~~
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:41:14: note:   no known conversion for argument 1 from ‘amrex::Box(amrex::IntVect*, amrex::IntVect*)’ to ‘const amrex::Box&’
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:39:5: note: candidate: amrex::Geometry::Geometry()
     Geometry ();
     ^~~~~~~~
/opt/src/amrex/amrex/Src/Base/AMReX_Geometry.H:39:5: note:   candidate expects 0 arguments, 1 provided
```

**Comment by WeiqunZhang** [comment] 2017-11-03 16:09
Thanks for reporting this!  The problem is due to the most vexing parse in C++.  https://en.wikipedia.org/wiki/Most_vexing_parse  It has now been fixed.  So I am going to close the issue.

**Closed by WeiqunZhang** 2017-11-03 16:09 UTC
