### ISSUE TITLE
Warn against using OpenMP with MFIter(boxarray, distribution_map)

### ISSUE THREAD

**Issue by maikel** [AMReX-Codes/amrex#675] opened 2020-01-27 09:47 UTC
The following code will (unpredictably) produce segmentation faults when using OpenMP, even in Debug mode, and is something is stumbled upon.

```
void g(const MFIter & mfi);
void ForEachSingleValuedGrid(const BoxArray& ba, const DistributionMapping& dm, const FabArray<EBCellFlagFab>& flags) {
#if defined(_OPENMP) && defined(AMREX_USE_OMP)
#pragma omp parallel
#endif
  for (MFIter mfi(ba, dm); mfi.isValid(); ++mfi) {
    if (flags[mfi].getType() == FabType::singlevalued) {
      g(mfi);
    }
  }
}
```

**Comment by WeiqunZhang** [comment] 2020-01-27 17:54
Thanks for reporting this.  The problem is `FabArray` constructor is not omp thread safe.  I made some changes in `weiqun/mfiter` branch.  Could you test it?  I tried to reproduce the segfault.  But since it's unpredictable, I was unable to get a segfault.

**Comment by maikel** [comment] 2020-01-30 09:04
This time I have not looked into the changes you made but with current develop (commit 132644d12847) I manage to reproduce the segfault as in 

```bash
$ mpirun --map-by socket:pe=20 ./examples/AMReX.EB.MultiTube --config ../FiniteVolumeSolver/examples/AMReX/EB/MultiTube.py
MPI initialized with 2 MPI processes
OMP initialized with 20 OMP threads
AMReX (132644d12847-dirty) initialized
Segfault
Segfault
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[37897,1],1] (PID 23841)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
See Backtrace.1.1 file for details
See Backtrace.1.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 11.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[gcn1010:23835] 1 more process has sent help message help-opal-runtime.txt / opal_init:warn-fork
[gcn1010:23835] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

But the error does not occur on the branch `weiqun/mfiter` (commit f51c71492fb2)

```bash
$ mpirun --map-by socket:pe=20 ./examples/AMReX.EB.MultiTube --config ../FiniteVolumeSolver/examples/AMReX/EB/MultiTube.py
MPI initialized with 2 MPI processes
OMP initialized with 20 OMP threads
AMReX (f51c71492fb2-dirty) initialized
2020-Jan-30 10:02:48.061944 -- [info] [T =  7.13218e-06s] [  0%] 00001: dt = 7.132179e-06s wall-time: 00h:00m:0.705674s (+1.035532e+00s)
2020-Jan-30 10:02:48.095615 -- [PressureValve] [info] [T =  7.13218e-06s] [level = 0] pressure valve changed to fuel!
2020-Jan-30 10:02:48.096094 -- [PressureValve] [info] [T =  7.13218e-06s] [level = 0] pressure valve changed to fuel!
2020-Jan-30 10:02:48.096463 -- [PressureValve] [info] [T =  7.13218e-06s] [level = 0] pressure valve changed to fuel!
2020-Jan-30 10:02:48.096801 -- [PressureValve] [info] [T =  7.13218e-06s] [level = 0] pressure valve changed to fuel!
2020-Jan-30 10:02:48.097133 -- [PressureValve] [info] [T =  7.13218e-06s] [level = 0] pressure valve changed to fuel!
2020-Jan-30 10:02:48.097489 -- [PressureValve] [info] [T =  7.13218e-06s] [level = 0] pressure valve changed to fuel!
2020-Jan-30 10:02:48.473513 -- [info] [T =  1.32079e-05s] [  0%] 00002: dt = 6.075702e-06s wall-time: 00h:00m:1.117243s (+4.115690e-01s)
2020-Jan-30 10:02:48.877560 -- [info] [T =  1.92879e-05s] [  0%] 00003: dt = 6.080017e-06s wall-time: 00h:00m:1.521289s (+4.040466e-01s)
2020-Jan-30 10:02:49.288750 -- [info] [T =  2.53722e-05s] [  0%] 00004: dt = 6.084278e-06s wall-time: 00h:00m:1.932476s (+4.111864e-01s)
2020-Jan-30 10:02:49.724793 -- [info] [T =  3.14606e-05s] [  0%] 00005: dt = 6.088468e-06s wall-time: 00h:00m:2.368517s (+4.360409e-01s)
[The  Pinned Arena] space (MB) used spread across MPI: [31 ... 31]
AMReX (f51c71492fb2-dirty) finalized
```

Looks good to me!

**Comment by WeiqunZhang** [comment] 2020-02-03 17:22
This has been merged into `development` branch.

**Closed by WeiqunZhang** 2020-02-03 17:22 UTC
