### ISSUE TITLE
HDF5 error on WriteSingleLevelPlotfileHDF5

### ISSUE THREAD

**Issue by mirenradia** [AMReX-Codes/amrex#4033] opened 2024-07-17 14:00 UTC
Since #4015, I have been getting the following HDF5 error when I call `WriteSingleLevelPlotfileHDF5`:
```
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: ../../src/H5Pdcpl.c line 2189 in H5Pget_chunk(): not a chunked storage layout
    major: Invalid arguments to routine
    minor: Bad value
```
Here are the relevant GNU Make configuration variables of my AMReX application:
```
DEBUG = FALSE
USE_MPI = FALSE
USE_HDF5 = TRUE
COMP = gnu
DIM = 3
```
I am building on my laptop running Fedora Linux 40 with the following package versions
* gcc 14.1.1-7.fc40
* hdf5-devel 1.12.1-15.fc40

FWIW, the `MultiFab` I'm writing is comprised of a single box of size $32^3$.

**Comment by WeiqunZhang** [comment] 2024-07-17 16:10
@arnav-singhal

**Comment by WeiqunZhang** [comment] 2024-07-17 16:22
Maybe we need to call `H5P_getlayout` to check if it's chunked data before calling `H5Pget_chunk`? @mirenradia Could you try?

**Comment by arnav-singhal** [comment] 2024-07-17 16:28
Yeah, pretty sure that's it. I'm testing it out locally right now.

**Comment by arnav-singhal** [comment] 2024-07-17 17:23
Reproduced and fixed in #4034. In the meantime, the hdf5 files generated by the bugged program should still be all good and readable, as far as I can tell.

**Closed as completed** 2024-07-17 18:56 UTC

**Comment by atmyers** [comment] 2024-07-17 18:57
@arnav-singhal Thanks for the fix! @mirenradia - could you verify that the issue is fixed on development and re-open this issue if not?

**Comment by mirenradia** [comment] 2024-07-18 09:36
I can confirm that #4034 has resolved the issue for me. Thanks for the quick bugfix @arnav-singhal!
