### ISSUE TITLE
CMake AMReX version error

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Codes/amrex#731] opened 2020-03-04 21:38 UTC
Hello, I am getting this error recently:
```
CMake Error at Submodules/AMReX/CMakeLists.txt:46 (project):
  VERSION "v0.1.146" format invalid.
```
I think it is due to https://github.com/AMReX-Codes/amrex/commit/15c6c1f8a9fa10630bac0089a994bf8602aa9f03

**Comment by mic84** [comment] 2020-03-04 23:13
Hi Jon, 
thank you for reporting this. I tried to reproduce this bug by building amrex as a standalone library and  building amrex as a subproject -- I think the latter is the strategy you use.  However, I did not have any issue in both scenarios. Could you provide me with a minimal setup that triggers this error? Thanks.

**Comment by jrood-nrel** [comment] 2020-03-04 23:15
Sure. I will try to provide one tomorrow. In the meantime, I saw this with CMake 3.16.4 if that makes a difference.

**Comment by mic84** [comment] 2020-03-04 23:31
Thanks. I just tried with CMake 3.16.2 but no luck so far.

**Comment by jrood-nrel** [comment] 2020-03-05 17:29
@mic84 Looking at the commit, this is a problem I have had in other projects using `git describe`. It is taking the version from my higher level git repo in which I have AMReX as a submodule. So I see this output:
```
% git describe
v0.1-150-g275a1d3
```
So I think this is a problem for multiple levels of git repos.

**Comment by mic84** [comment] 2020-03-05 18:22
@jrood-nrel I just committed a fix to this issue. Can you try the latest development branch and let me know if you still experience any problem? Thanks!

**Comment by jrood-nrel** [comment] 2020-03-05 18:54
Works! Thanks!

**Comment by maikel** [comment] 2020-03-07 11:16
I still get the following error 

> VERSION "de5c1930bbc1" format invalid.

**Comment by maikel** [comment] 2020-03-08 09:15
My current workaround is to explicitly set `AMREX_PKG_VERSION` to a valid version number when configuring `cmake`.

**Comment by mic84** [comment] 2020-03-09 17:15
@maikel can you provide a minimal setup so I can reproduce the error?

**Comment by ax3l** [comment] 2020-04-04 01:25
@maikel did you do a shallow checkout of the branch/repo? That would explain why `git describe` cannot find a related versioned tag.

**Comment by ax3l** [comment] 2020-04-04 01:46
Fix provided via https://github.com/AMReX-Codes/amrex/pull/755

**Comment by jrood-nrel** [comment] 2020-04-09 23:08
I'm seeing this again on a certain system I am using:
```
CMake Error at submods/amrex/CMakeLists.txt:54 (project):
  VERSION "3f1e6e06bc33" format invalid.
```

**Comment by ax3l** [comment] 2020-04-09 23:14
@jrood-nrel can you try again with the latest development branch? We landed a patch in #755 that addresses this, according to my tests.

**Comment by jrood-nrel** [comment] 2020-04-09 23:18
`3f1e6e06bc33` is the latest AMReX development which appears to be where this version number is coming from.

**Comment by jrood-nrel** [comment] 2020-04-09 23:19
I only see this on Github CI systems, but I haven't seen it anywhere else. So maybe it's checking out in some way I don't understand.

**Comment by ax3l** [comment] 2020-04-09 23:35
Looks like the CI checks out the right commit of AMReX, probably as a shallow clone without tags. This is totally fine, but somehow slips through the "this commit hash ain't no version number" check.

**Comment by ax3l** [comment] 2020-04-09 23:38
Ha, I checked with a different hash last time!
`3f1e6e06bc33` starts with a `3` and gets interpreted as version "3.0.0" ^^

**Comment by ax3l** [comment] 2020-04-09 23:53
More robust fix proposed in https://github.com/AMReX-Codes/amrex/pull/759

**Comment by ax3l** [comment] 2020-04-10 00:01
@jrood-nrel can you try updating the the latest HEAD of `development` again?

**Comment by jrood-nrel** [comment] 2020-04-10 15:27
Looks like it works again. Thanks!

**Closed** 2020-04-10 18:16 UTC
Labels: install
